version: "3.5"

networks:
  laravel:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:8.0.15
    container_name: mysql
    restart: unless-stopped
    command:
      --default-authentication-plugin=mysql_native_password
      --perfomance-schema --secure-file-priv=""
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: ./docker/Fpm.Dockerfile
    container_name: php
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel
